### ISSUE TITLE
Error with pnpm

### ISSUE THREAD

**Issue by jbboehr** [dividab/tsconfig-paths-webpack-plugin#18]
Usage with `pnpm` fails. The error that is produced is identical to #14.

Based on the code, `enhanced-resolve` is not a `devDependency`: https://github.com/dividab/tsconfig-paths-webpack-plugin/blob/7620f58eff62b04e03243cd345a592209cff3cd5/src/plugin.ts#L126

**Comment by jonaskello** [comment]
I'm quite sure that enhanced-resolve is needed at run-time as mentioned in #14, so for that it needs to be in the `dependencies` section of package.json. I'm not familiar with pnpm but `devDependencies` should only be needed during development and not when you use the plugin in run-time, so I'm not sure I understand this issue. Could you elaborate on why it would be needed in `devDependencies` section? I

**Comment by jbboehr** [comment]
@jonaskello Are you asking me? Because it sounds like we're saying the same thing: `enhanced-resolve` belongs in `dependencies` *not* `devDependencies`.

**Comment by jbboehr** [comment]
In the master branch, it's in `devDependencies`.

**Comment by jonaskello** [comment]
Aha, then I get it. I was thrown off by this comment in the first post:

> Based on the code, enhanced-resolve is not a devDependency

I thought you were saying it was currently not in the `devDependency` section in package.json. But reading it more carefully I see now you meant it was used at run-time in the code :-). I'll merge the PR and release!

**Comment by jbboehr** [comment]
Thank you! I could've worded it more carefully.
