### ISSUE TITLE
monorepo proj can not found main entry

### ISSUE THREAD

**Issue by lichnow** [dividab/tsconfig-paths-webpack-plugin#47]
lerna.js+monorepo and webpack use this plugin not work
```
Error: Cannot find module 'xxx/node_modules/@test/core/dist/index.js'. Please verify that the package.json has a valid "main" entry
```
detail
```
code: 'MODULE_NOT_FOUND',
path: '/xxx/Code/test/node_modules/@test/core/package.json',
requestPath: '@test/core'
```

but I only need to compile `@test/server` to run node

plugin used like `new TsconfigPathsPlugin({
                configFile: config.tsconfig,
                mainFields: ['module', 'main', 'index'],
})`

tsconfig for `@test/server`
```
"baseUrl": ".",
 "paths": {
         "@test/*": ["./packages/*/src","./apps/*/src"]
 }
```

and `@test/core` package.json 
```
"main": "dist/index.js",
"module": "src/index.ts",
```
Has any thing to solve it? thx

**Comment by castroCrea** [comment]
Did you solve it?
