### ISSUE TITLE
TsconfigPathsPlugin type not compatible with webpack 5

### ISSUE THREAD

**Issue by brett-east** [dividab/tsconfig-paths-webpack-plugin#65]
I'm trying to upgrade to webpack 5, but I'm now getting a type error when
trying to use the TsconfigPathsPlugin.

```js
resolve: {
    extensions: [...],

    // resolve aliases from tsconfig.server.json
    plugins: [
      new TsconfigPathsPlugin({ // type error here
        configFile: './tsconfig.server.json',
      }),
    ],

    alias: {...},
},
```

I get the following error:

```
Type 'TsconfigPathsPlugin' is not assignable to type '"..." | ResolvePluginInstance'.
Type 'TsconfigPathsPlugin' is not assignable to type 'ResolvePluginInstance'.
Types of property 'apply' are incompatible.
```

I have the feeling that this isn't a widespread issue as I can't see any mention 
of it in other places, but I would have thought that I'd be able to find at least someone
that has come across the same problem.

**Comment by MitchTalmadge** [comment]
Is this the same as #61 ?

**Comment by brett-east** [comment]
> Is this the same as #61 ?

It is, sorry, I forgot I even commented on #61. I'm going to close this in favour of that issue.
