### ISSUE TITLE
'husky' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by FluffBallDev** [dividab/tsconfig-paths-webpack-plugin#67]
Cannot install this from NPM because Husky fails to run at post install

317 error code ELIFECYCLE
318 error errno 1
319 error tsconfig-paths-webpack-plugin@3.4.0 postinstall: `husky install`
319 error Exit status 1
320 error Failed at the tsconfig-paths-webpack-plugin@3.4.0 postinstall script.
320 error This is probably not a problem with npm. There is likely additional logging output above.
321 verbose exit [ 1, true ]

**Comment by jonaskello** [comment]
Husky 5 uses a new config model and recommended postinstall script but that does not make sense since it should only be used in development. Changed it to prepare script and this should be fixed in 3.4.1. Please try the new version :-).
