### ISSUE TITLE
[3.5.0] Build spamming "Returning with path..." logs

### ISSUE THREAD

**Issue by olee** [dividab/tsconfig-paths-webpack-plugin#71]
Just updated to 3.5.0 and now the webpack build spams hundreds of log messages caused by this line: https://github.com/dividab/tsconfig-paths-webpack-plugin/blob/master/src/plugin.ts#L299

**Comment by danikenan** [comment]
also, `log*` and `silent` has no effect on this!

**Comment by jonaskello** [comment]
Should be fixed now in 3.5.1.

**Comment by visualfanatic** [comment]
Thank you @jonaskello for the instant release!
