### ISSUE TITLE
Incompatible types with latest version

### ISSUE THREAD

**Issue by hungtcs** [dividab/tsconfig-paths-webpack-plugin#91]
https://github.com/dividab/tsconfig-paths-webpack-plugin/blob/cb0f1dd86f9ca12818703ccbff13f7121ce210d6/src/plugin.temp.types.ts#L1-L7

Now it has been exported by webpack: [webpack/types.d.ts#L13159](https://github.com/webpack/webpack/blob/8f87b50dc7ac24eb5c91fd0d55a22e34e252863c/types.d.ts#L13159)

Since: [webpack@5.65.0](https://github.com/webpack/webpack/releases/tag/v5.65.0)
Commit: https://github.com/webpack/webpack/commit/791347fc91c16cd00c7be4e6f5de65727337f8d1

Webpack version: 5.74.0

**Comment by aKzenT** [comment]
I'm encountering this issue as well. Are there plans to release a new version soon? Thanks!

**Comment by jonaskello** [comment]
@aKzenT You can try 4.0.0 which was released today.
