### ISSUE TITLE
Warning on missing baseUrl in 4.0.0 even though it can be undefined

### ISSUE THREAD

**Issue by tooga** [dividab/tsconfig-paths-webpack-plugin#99]
Hi,

The 4.0.0 version has updated the `tsconfig-paths` dependency also to 4.0.0.

In `tsconfig-paths` 4.0.0 the `baseUrl` in tsconfig can also be undefined (https://github.com/dividab/tsconfig-paths/pull/208). Still, this plugin returns "Found no baseUrl in tsconfig.json, not applying tsconfig-paths-webpack-plugin" as a result of missing `baseUrl`.

**Comment by jonaskello** [comment]
Yes this check should be removed now then. I think we could consider it a bug that it is still there so it could be released quickly in a patch version.

@tooga Would you care to submit a PR to fix it?

**Comment by alfaproject** [comment]
Just stumbled upon this ):

**Comment by sverweij** [comment]
Hi @jonaskello I've made a small PR (#105) to fix this issue as well as issue #59  - but not sure to have followed the right protocol for this project. Is there something I can/ need to do  to further the resolution?

**Comment by jonaskello** [comment]
Released in 4.1.0
